version: "3.1"

services:
  db:
    image: mysql/mysql-server:8.0.23
    container_name: db_ct
    ports:
      - 32000:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: ./
      dockerfile: flask_app/Dockerfile
    image: task_api_server:0.0.1
    container_name: flask_ct
    ports:
      - ${API_PORT}:6000
    depends_on:
      - db
    restart: always
    working_dir: /flask-app
    environment:
      - FLASK_APP=main.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: sh entrypoint.sh
